- name: variables demo
  hosts: local
  connection: local
  vars:
   COURSE: "DEVOPS"
   TRAINER: "SIVA"
  tasks:
   - name: variables demo
     ansible.builtin.debug:
      msg: "I am {{ TRAINER }}. You are learning {{ COURSE }}."
