- name: Install nginx and run
  hosts: frontend
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.package:
     name: nginx
     state: present
  - name: Enable nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes