- name: prompt variables
  hosts: local
  connection: local
  vars_prompt:
  - name: Username
    prompt: "Enter username"
    private: no
  - name: Password
    prompt: "Enter password"
    private: yes
  tasks: 
  - name: prompt variables
    ansible.builtin.debug:
     msg: "ur username is {{ Username }}, password is {{ Password }}"