- name: variables as arguments 
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
     msg: "This is {{ COURSE }} coaching by {{ TRAINER }} in {{ DURATION }}"