- name: loops
  hosts: localhost
  connection: local
  tasks:
  - name: print names using loop
    ansible.builtin.debug:
     msg: "hello {{ item }}"
    loop:
     - suresh
     - mahesh
     - ramesh